### ISSUE TITLE
Add Sharing Controls to Form Submission

### ISSUE THREAD

**Issue by silent1mezzo** [my-covid-story/www#10]
Relies on https://github.com/my-covid-story/www/issues/6

- [ ] Where would you like your story to be shared? (Checkboxes)
- [ ] What information would you like to share along with your story? (Checkboxes)
- [ ]  Can a journalist contact you for more information or an interview (Radio buttons)
- [ ] If yes, please enter your preferred method of contact (text box)

**Comment by mwickett** [comment]
@silent1mezzo Can we close this one?
