### ISSUE TITLE
Will this project be going global?

### ISSUE THREAD

**Issue by LuckeeDev** [my-covid-story/www#110]
I'm an Italian student who had a very similar idea to the project you're developing and I would love to contribute and see it available globally, even outside Canada. Do you think it's something that could be done?

**Comment by LuckeeDev** [comment]
Related to #107: if this is something that you're interested in, I could work on Italian and German translations.

**Comment by mwickett** [comment]
Hey @LuckeeDev - thanks for opening the issue. This is something that we've had early conversations about as a team (there are about 20 other non-dev people from Ontario, Canada involved in the project). We don't have any concrete plans yet for support beyond Canada (and are currently really just focused on the province of Ontario), but it's still _really_ early (this has only been a project for just over a week now).

I'm going to leave this open just as a way to gauge demand - others who are interested should comment.

We are gearing up to get localization going, so we'll tap you when that's ready - help with translation would be amazing!

**Comment by LuckeeDev** [comment]
Okay, awesome! Thanks for the response @mwickett.
