### ISSUE TITLE
Update schema for SEO

### ISSUE THREAD

**Issue by kapilharesh** [my-covid-story/www#122]
Include the following schema into the head of the HTML page to aid in SEO

`<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "MyCovidStory",
  "alternateName": "MyCovidStory.ca",
  "url": "https://MyCovidStory.ca",
  "logo": "",
  "sameAs": [
    "https://www.facebook.com/MyCovidStoryCA",
    "https://twitter.com/MyCOVIDStory_CA",
    "https://www.instagram.com/MyCovidStory_CA/",
    "https://github.com/my-covid-story/www",
    "https://MyCovidStory.ca"
  ]
}
</script>`

**Comment by ryanwelcher** [comment]
This was addressed with #125.

**Comment by silent1mezzo** [comment]
Thanks so much @ryanwelcher
