### ISSUE TITLE
404 page with undraw svg

### ISSUE THREAD

**Issue by curtis-vdg** [my-covid-story/www#127]
Added image that can be exported from Figma as an svg or other file type.

https://www.figma.com/file/hwuWoqcVWWWrukev8pl9rn/My-Covid-Story?node-id=752%3A0

**Comment by LuckeeDev** [comment]
I can work on this as soon as #111 gets merged!

**Comment by curtis-vdg** [comment]
Awesome. I liked the Unddraw idea @LuckeeDev
