### ISSUE TITLE
Trim social share description content to closest sentence end.

### ISSUE THREAD

**Issue by mwickett** [my-covid-story/www#138]
When we generate the snippet of story content that gets shared on social, we should remove 'widowed' sentence fragments by trimming back to the closest period. Small enhancement, but looks a lot cleaner. 

![CleanShot 2021-04-28 at 10 00 33@2x](https://user-images.githubusercontent.com/845983/116416814-aec0ae80-a808-11eb-91e5-3307841bc71b.png)

**Comment by silent1mezzo** [comment]
@mwickett This could potentially remove a lot if people have run-on sentences. thoughts on just trimming to the last word and adding `...`

**Comment by LuckeeDev** [comment]
@silent1mezzo yes, this looks like the best option!

**Comment by mwickett** [comment]
Oh yeah, way better idea @silent1mezzo!
