### ISSUE TITLE
SSG issues

### ISSUE THREAD

**Issue by LuckeeDev** [my-covid-story/www#141]
The last three stories appear to be a 404. In order, they're:
- https://www.mycovidstory.ca/story/cko1c5rjr00000wmpc4hflovj
- https://www.mycovidstory.ca/story/cko0y7an100000uicm6no6sdi
- https://www.mycovidstory.ca/story/cko0wwoqb00000wlayrilr73u

I suspect the issue lies in the SSG strategy the website is currently using... the stories were probably added after the last build and therefore were not picked up by the static site generator. I think that moving forward we should ditch full SSG because it will also make the build times grow exponentially as the number of story grows, and we should look into [incremental static regeneration](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration). The problem with the latter is that it requires a running Node server to statically regenerate the pages, so we should also move away from Vercel.

What do you think?

**Comment by silent1mezzo** [comment]
@LuckeeDev we currently revalidate every minute (https://github.com/my-covid-story/www/blob/main/pages/index.tsx#L39) which pulls all of the new pages down. I'm definitely curious as to why those pages were 404'ing. Two of the three seem to have fixed themselves which is even more curious.

**Comment by LuckeeDev** [comment]
> we currently revalidate every minute (https://github.com/my-covid-story/www/blob/main/pages/index.tsx#L39) which pulls all of the new pages down.

Yep sorry, my bad. I just looked through the code and I saw the revalidation. I also just learned that Vercel supports revalidation!

> I'm definitely curious as to why those pages were 404'ing. Two of the three seem to have fixed themselves which is even more curious.

Yes that's weird, the middle one is still 404'ing though.

**Comment by LuckeeDev** [comment]
The problem persists if the pages are visited from the homepage instead of a link.

**Comment by LuckeeDev** [comment]
Now they're all fixed. Do you think there's a way to avoid this weird behaviour @silent1mezzo?

**Comment by mwickett** [comment]
I think it's an issue with the error page being returned from getStaticProps being cached on the individual story view. I didn't think that through on your PR @LuckeeDev 

We should try removing that catch and see.

**Comment by LuckeeDev** [comment]
Yeah I can dig more into this issue today :)

**Comment by LuckeeDev** [comment]
I'm thinking about how we should handle this, which is also somewhat related to #126.

To me, this looks like the best approach, but I'm completely open to any suggestion:
- Instead of returning a `success` prop inside `getStaticProps()` for the `[id].tsx`, we should return an object with the following structure `{ notFound: true, revalidate: 60 }` as described [here](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) if the story is not found. This will allow to return a true 404 status to the client and will still revalidate the path every minute.
- While the page is loading in the background, I think that we should display a loading component, to show the user that something is happening, instead of needing to wait until the full page is loaded on the server. (This is only needed for the first visit to every page, but it's a nice improvement for the first user which hits that page). This change would be implemented by using `fallback: true` instead of `fallback: 'blocking'` as described [here](https://nextjs.org/docs/basic-features/data-fetching#when-is-fallback-true-useful).
- [OPTIONAL] Instead of generating all paths via `getStaticPaths()`, we should only generate the latest 20 - 50 stories and then leave the rest up to incremental static regeneration. In the long run, this will be a massive improvement.

I'm looking forward to hearing your opinion on this! @mwickett @silent1mezzo
