### ISSUE TITLE
Add `/about` page

### ISSUE THREAD

**Issue by mwickett** [my-covid-story/www#42]
See [Figma](https://www.figma.com/file/hwuWoqcVWWWrukev8pl9rn/My-Covid-Story?node-id=195%3A5244) for content

![About Us - Full Copy](https://user-images.githubusercontent.com/845983/115451427-2c723200-a1eb-11eb-80af-5f90dd175599.jpg)

**Comment by silent1mezzo** [comment]
hmm, seems like this content is exactly the same for the FAQ.

**Comment by JamiesonRoberts** [comment]
Launched in PR #53
