### ISSUE TITLE
Submission Form

### ISSUE THREAD

**Issue by silent1mezzo** [my-covid-story/www#6]
Basic Overview:
Welcome/Intro
Data governance stuff
Form
- [x] I am a [dropdown]
- [x] Are you sharing your own story or someone else's [dropdown]
- [x] Postal Code [text box]
- [x] Name [text box]
- [x] Tell us your story [text box] (prompt: "Please share your Covid story with us")

PRD Link: https://docs.google.com/document/d/13w_pOfNRXx9BiDL9nh6AbMR50wi9xjRZtlv9divlJDc/edit?pli=1#heading=h.twy5jk5i31u8

**Comment by mwickett** [comment]
This is WIP - I've got the basic piping working and am adding fields. It's a single component for now, and that'll get put into the `/stories/create` page.
