### ISSUE TITLE
List all stories on /

### ISSUE THREAD

**Issue by silent1mezzo** [my-covid-story/www#8]
- [x] API rework (to support server-side and client-side rendering)
- [x] Basic stories feed at `/stories`
- [ ] More responsive layout
- [x] Background images (one from each category-based collection)
- [ ] [FSA](https://en.wikipedia.org/wiki/Postal_codes_in_Canada#Forward_sortation_areas) to city mapping
- [x] Single story details at `/stories:id`
- [x] Navigation from feed to single story
- [x] Include name for display, but only if not anonymous

**Comment by davesteinberg** [comment]
I'm working on this. Looks like I don't have permission to assign it to myself.

**Comment by davesteinberg** [comment]
I have created PR #20 to tidy up the API a bit, but haven't made any real progress on the UI. If anyone wants to work on this during the day tomorrow, please feel free. Otherwise, I'll pick it up again in the evening.

**Comment by mwickett** [comment]
🎉 Big ❤️  to @davesteinberg on this one.
