### ISSUE TITLE
Responsive layout for single story (story detail) page

### ISSUE THREAD

**Issue by davesteinberg** [my-covid-story/www#84]
Currently, it doesn't look fantastic on a desktop browser. Design is in Figma (thanks Curtis!):
https://www.figma.com/file/hwuWoqcVWWWrukev8pl9rn/My-Covid-Story?node-id=42%3A0

**Comment by davesteinberg** [comment]
I'll do this one next.

**Comment by silent1mezzo** [comment]
Closed out by https://github.com/my-covid-story/www/pull/108
